### ISSUE TITLE
evaluation indicator

### ISSUE THREAD

**Issue by BKINGING** [Micro-han/End-to-end-SegmentAnything3D#1]
Are you going to publish the metrics code?

**Comment by Micro-han** [comment]
I think it's hard to calculate the mIou, SAM3D's output does not contain the semantic informantion, and in SegmentAnything3D's arxiv I can not find the metrics either.

**Comment by BKINGING** [comment]
Is there no quantitative way to evaluate it?

**Comment by Micro-han** [comment]
Maybe u can calculate the mIoU through the distance of GT and instance.

**Comment by BKINGING** [comment]
Do you have any future metrics to evaluate your code?

**Comment by Micro-han** [comment]
I just use it as a tool, by now I do not pay attention to the metrics. Maybe in the future I will use mIoU as the metrics, and use the distance to establish the relationship bewteen the gt and the instance.

**Comment by BKINGING** [comment]
Ok, thank you

**Comment by Micro-han** [comment]
> Ok, thank you

Hey, I read [this paper](https://arxiv.org/abs/2312.08372) recently, and I find they use mAP, AP_25, AP_50 as the metrics.
